checks:
  php: true

filter:
  excluded_paths:
    - tests/*

build:
  nodes:
    analysis:
      tests:
        override:
          - php-scrutinizer-run
          - command: phpcs-run
            use_website_config: false
    php74:
      environment:
        php:
          version: 7.4
      tests:
        override:
          - command: ./vendor/bin/phpunit --coverage-clover=my-coverage-file
            coverage:
              file: my-coverage-file
              format: php-clover
    php80:
      environment:
        php:
          version: 8.0
      tests:
        override:
          - command: php -dxdebug.mode=coverage ./vendor/bin/phpunit --coverage-clover=my-coverage-file
            coverage:
              file: my-coverage-file
              format: php-clover
